name: Run refresh cache script

on:
  schedule:
  - cron: '0 22 * * *'  # This cron expression triggers the workflow daily at 6 am UTC
  workflow_dispatch:       # Allow manual triggering of the workflow

jobs:
  refresh_cache:
    runs-on: ubuntu-latest

    steps:
      - name: Make POST request to refresh Streamlit cache
        run: |
          curl -X POST https://optilens.streamlit.app/refresh-cache