name: Run alerting script

on:
  schedule:
  - cron: '0 20 * * *'  # This cron expression triggers the workflow daily at 8 PM
  workflow_dispatch:       # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      env: # Or as an environment variable
        TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python alert_script.py